const restaurantList = [
  {
    id: "474835",
    name: "Khaleez Restaurant",
    cloudinaryImageId: "zijocs9t8fihfly6mozo",
    locality: "Pottathapdi\n",
    areaName: "Tirur Locality",
    costForTwo: "₹400 for two",
    cuisines: ["South Indian", "Biryani", "Kerala", "Beverages"],
    avgRating: 4.2,
    parentId: "285754",
    avgRatingString: "4.2",
    totalRatingsString: "500+",
    sla: {
      deliveryTime: 31,
      lastMileTravel: 4.3,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "4.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },

  {
    id: "7572782",
    name: "LAZEEZ MUGHLAI RESTAURANT",
    cloudinaryImageId: "8e82f6e42f5e5bde0649f1f8f48209d8",
    locality: "Tirur Co Operative Rural Bank",
    areaName: "Tirur",
    costForTwo: "₹350 for two",
    cuisines: ["Mughlai", "North Indian", "South Indian", "Beverages"],
    avgRating: 3.8,
    parentId: "447872",
    avgRatingString: "3.8",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 46,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "45-50 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "4802583",
    name: "Spunge cakes and cafe",
    cloudinaryImageId: "hewjd0efyoc9flbkiudo",
    locality: "Ring Road\n",
    areaName: "Ring Road , Tirur",
    costForTwo: "₹350 for two",
    cuisines: ["Desserts", "Pizzas", "Beverages"],
    avgRating: 4.2,
    parentId: "288528",
    avgRatingString: "4.2",
    totalRatingsString: "50+",
    sla: {
      deliveryTime: 51,
      lastMileTravel: 4.7,
      serviceability: "SERVICEABLE",
      slaString: "50-55 mins",
      lastMileTravelString: "4.7 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },

  {
    id: "5188948",
    name: "Domino's Pizza",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/8/a5da1ec2-d27d-4947-908c-fce64cf6fc24_518894.jpg",
    locality: "Ring Road",
    areaName: "Kottakkal",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.3,
    parentId: "2456",
    avgRatingString: "4.3",
    totalRatingsString: "50+",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 4.1,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "4.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "7572788",
    name: "LAZEEZ MUGHLAI RESTAURANT",
    cloudinaryImageId: "8e82f6e42f5e5bde0649f1f8f48209d8",
    locality: "Tirur Co Operative Rural Bank",
    areaName: "Tirur",
    costForTwo: "₹350 for two",
    cuisines: ["Mughlai", "North Indian", "South Indian", "Beverages"],
    avgRating: 3.8,
    parentId: "447872",
    avgRatingString: "3.8",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 46,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "45-50 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "4756798",
    name: "Hotel Sabka",
    cloudinaryImageId: "bejrulpvhwh3dsdbfquv",
    locality: "Tirur Road",
    areaName: "Thazhe Palam",
    costForTwo: "₹300 for two",
    cuisines: ["Biryani", "Chinese", "Arabian", "Seafood", "Kerala", "Snacks"],
    avgRating: 4,
    parentId: "285944",
    avgRatingString: "4.0",
    totalRatingsString: "500+",
    sla: {
      deliveryTime: 41,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "40-45 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "6690381",
    name: "FAVOUREAT BURGER",
    cloudinaryImageId: "2fef59a8d61cc3861c8f0fc1cbf12a8c",
    locality: "Thazhepalam",
    areaName: "Tirur",
    costForTwo: "₹200 for two",
    cuisines: ["Fast Food", "Beverages", "Juices"],
    avgRating: 3.8,
    parentId: "401099",
    avgRatingString: "3.8",
    totalRatingsString: "20+",
    sla: {
      deliveryTime: 40,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "35-40 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "4748479",
    name: "Sabka Restaurant",
    cloudinaryImageId: "oe28gebhd7mq2gfg7lri",
    locality: "Ring Road",
    areaName: "Tirur",
    costForTwo: "₹300 for two",
    cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
    avgRating: 3.9,
    parentId: "454615",
    avgRatingString: "3.9",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 41,
      lastMileTravel: 5,
      serviceability: "SERVICEABLE",
      slaString: "40-45 mins",
      lastMileTravelString: "5.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "48025890",
    name: "Spunge cakes and cafe",
    cloudinaryImageId: "hewjd0efyoc9flbkiudo",
    locality: "Ring Road\n",
    areaName: "Ring Road , Tirur",
    costForTwo: "₹350 for two",
    cuisines: ["Desserts", "Pizzas", "Beverages"],
    avgRating: 4.2,
    parentId: "288528",
    avgRatingString: "4.2",
    totalRatingsString: "50+",
    sla: {
      deliveryTime: 51,
      lastMileTravel: 4.7,
      serviceability: "SERVICEABLE",
      slaString: "50-55 mins",
      lastMileTravelString: "4.7 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },

  {
    id: "51889455",
    name: "Domino's Pizza",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/8/a5da1ec2-d27d-4947-908c-fce64cf6fc24_518894.jpg",
    locality: "Ring Road",
    areaName: "Kottakkal",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.3,
    parentId: "2456",
    avgRatingString: "4.3",
    totalRatingsString: "50+",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 4.1,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "4.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "9146744",
    name: "Memorice",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/25/39fe6079-b978-4b23-ae37-acc65e274760_914674.jpg",
    locality: "PSM COMPLEX",
    areaName: "Tirur",
    costForTwo: "₹299 for two",
    cuisines: ["Ice Cream"],
    veg: true,
    parentId: "362078",
    avgRatingString: "NEW",
    sla: {
      deliveryTime: 32,
      lastMileTravel: 4.3,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "4.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    name: "Memorice",
    id: "91467477",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/25/39fe6079-b978-4b23-ae37-acc65e274760_914674.jpg",
    locality: "PSM COMPLEX",
    areaName: "Tirur",
    costForTwo: "₹299 for two",
    cuisines: ["Ice Cream"],
    avgRatingString: "NEW",
    sla: {
      deliveryTime: 32,
      lastMileTravel: 4.3,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "4.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },

  {
    id: "816835",
    name: "Zargoza Container Cafe",
    cloudinaryImageId: "7758f29af04da5790cf12bdd053671b4",
    locality: "Tirur",
    areaName: "Tirur",
    costForTwo: "₹299 for two",
    cuisines: ["Beverages", "Chinese", "Snacks"],
    avgRating: 3.8,
    parentId: "486747",
    avgRatingString: "3.8",
    totalRatingsString: "5",
    sla: {
      deliveryTime: 32,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "472606",
    name: "Chicking",
    cloudinaryImageId: "yivby7t3s9lgdn6uystl",
    locality: "Kottakkal",
    areaName: "Tirur",
    costForTwo: "₹500 for two",
    cuisines: ["American", "Beverages", "Pizzas", "Burgers"],
    avgRating: 4,
    parentId: "251",
    avgRatingString: "4.0",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 38,
      lastMileTravel: 3.9,
      serviceability: "SERVICEABLE",
      slaString: "35-40 mins",
      lastMileTravelString: "3.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "496899",
    name: "The Quench",
    cloudinaryImageId: "fkofepr7nklrztzxglvw",
    locality: "B P Angadi ",
    areaName: "Thalakkad",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "South Indian", "Chinese"],
    avgRating: 4,
    parentId: "289012",
    avgRatingString: "4.0",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 34,
      lastMileTravel: 6.1,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "6.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "553632",
    name: "Faloodays",
    cloudinaryImageId: "pyqgde29m1ivfzp1x7p6",
    locality: "Vailathur Road",
    areaName: "Panbazar, Tirur",
    costForTwo: "₹250 for two",
    cuisines: [
      "Desserts",
      "Juices",
      "Beverages",
      "Burgers",
      "Rolls & Wraps",
      "Ice Cream",
    ],
    avgRating: 3.6,
    parentId: "333123",
    avgRatingString: "3.6",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 33,
      lastMileTravel: 4.2,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "4.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
];

export default restaurantList;
